// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/books/:bookId": {
    params: {
      "bookId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/completed": {
    params: {};
  };
  "/profile/dropped": {
    params: {};
  };
  "/profile/on-hold": {
    params: {};
  };
  "/profile/reading": {
    params: {};
  };
  "/profile/cms/genres": {
    params: {};
  };
  "/profile/cms/authors": {
    params: {};
  };
  "/profile/cms/books": {
    params: {};
  };
  "/api/auth/sign-in": {
    params: {};
  };
  "/api/auth/sign-up": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/send-feedback": {
    params: {};
  };
  "/api/cms/create-genre": {
    params: {};
  };
  "/api/cms/delete-genre": {
    params: {};
  };
  "/api/cms/edit-genre": {
    params: {};
  };
  "/api/cms/create-author": {
    params: {};
  };
  "/api/cms/delete-author": {
    params: {};
  };
  "/api/cms/edit-author": {
    params: {};
  };
  "/api/cms/create-book": {
    params: {};
  };
  "/api/cms/delete-book": {
    params: {};
  };
  "/api/cms/edit-book": {
    params: {};
  };
  "/api/cms/edit-book-genres": {
    params: {};
  };
  "/api/cms/edit-book-authors": {
    params: {};
  };
  "/api/set-book-status": {
    params: {};
  };
  "/api/unset-book-status": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/books/:bookId" | "/profile" | "/profile/completed" | "/profile/dropped" | "/profile/on-hold" | "/profile/reading" | "/profile/cms/genres" | "/profile/cms/authors" | "/profile/cms/books" | "/api/auth/sign-in" | "/api/auth/sign-up" | "/api/auth/logout" | "/api/send-feedback" | "/api/cms/create-genre" | "/api/cms/delete-genre" | "/api/cms/edit-genre" | "/api/cms/create-author" | "/api/cms/delete-author" | "/api/cms/edit-author" | "/api/cms/create-book" | "/api/cms/delete-book" | "/api/cms/edit-book" | "/api/cms/edit-book-genres" | "/api/cms/edit-book-authors" | "/api/set-book-status" | "/api/unset-book-status";
  };
  "routes/layout.tsx": {
    id: "common";
    page: "/" | "/search" | "/books/:bookId" | "/profile" | "/profile/completed" | "/profile/dropped" | "/profile/on-hold" | "/profile/reading" | "/profile/cms/genres" | "/profile/cms/authors" | "/profile/cms/books" | "/api/auth/sign-in" | "/api/auth/sign-up" | "/api/auth/logout" | "/api/send-feedback" | "/api/cms/create-genre" | "/api/cms/delete-genre" | "/api/cms/edit-genre" | "/api/cms/create-author" | "/api/cms/delete-author" | "/api/cms/edit-author" | "/api/cms/create-book" | "/api/cms/delete-book" | "/api/cms/edit-book" | "/api/cms/edit-book-genres" | "/api/cms/edit-book-authors" | "/api/set-book-status" | "/api/unset-book-status";
  };
  "routes/home/home.tsx": {
    id: "routes/home/home";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/book/book.tsx": {
    id: "routes/book/book";
    page: "/books/:bookId";
  };
  "routes/profile/profile.tsx": {
    id: "profile-layout";
    page: "/profile" | "/profile/completed" | "/profile/dropped" | "/profile/on-hold" | "/profile/reading" | "/profile/cms/genres" | "/profile/cms/authors" | "/profile/cms/books";
  };
  "routes/profile/tracking/to-read.tsx": {
    id: "routes/profile/tracking/to-read";
    page: "/profile";
  };
  "routes/profile/tracking/completed.tsx": {
    id: "routes/profile/tracking/completed";
    page: "/profile/completed";
  };
  "routes/profile/tracking/dropped.tsx": {
    id: "routes/profile/tracking/dropped";
    page: "/profile/dropped";
  };
  "routes/profile/tracking/on-hold.tsx": {
    id: "routes/profile/tracking/on-hold";
    page: "/profile/on-hold";
  };
  "routes/profile/tracking/reading.tsx": {
    id: "routes/profile/tracking/reading";
    page: "/profile/reading";
  };
  "routes/profile/cms/genres/genres.tsx": {
    id: "routes/profile/cms/genres/genres";
    page: "/profile/cms/genres";
  };
  "routes/profile/cms/authors/authors.tsx": {
    id: "routes/profile/cms/authors/authors";
    page: "/profile/cms/authors";
  };
  "routes/profile/cms/books/books.tsx": {
    id: "routes/profile/cms/books/books";
    page: "/profile/cms/books";
  };
  "routes/api/sign-in.ts": {
    id: "routes/api/sign-in";
    page: "/api/auth/sign-in";
  };
  "routes/api/sign-up.ts": {
    id: "routes/api/sign-up";
    page: "/api/auth/sign-up";
  };
  "routes/api/logout.ts": {
    id: "routes/api/logout";
    page: "/api/auth/logout";
  };
  "routes/api/send-feedback.ts": {
    id: "routes/api/send-feedback";
    page: "/api/send-feedback";
  };
  "routes/api/cms/create-genre.ts": {
    id: "routes/api/cms/create-genre";
    page: "/api/cms/create-genre";
  };
  "routes/api/cms/delete-genre.ts": {
    id: "routes/api/cms/delete-genre";
    page: "/api/cms/delete-genre";
  };
  "routes/api/cms/edit-genre.ts": {
    id: "routes/api/cms/edit-genre";
    page: "/api/cms/edit-genre";
  };
  "routes/api/cms/create-author.ts": {
    id: "routes/api/cms/create-author";
    page: "/api/cms/create-author";
  };
  "routes/api/cms/delete-author.ts": {
    id: "routes/api/cms/delete-author";
    page: "/api/cms/delete-author";
  };
  "routes/api/cms/edit-author.ts": {
    id: "routes/api/cms/edit-author";
    page: "/api/cms/edit-author";
  };
  "routes/api/cms/create-book.ts": {
    id: "routes/api/cms/create-book";
    page: "/api/cms/create-book";
  };
  "routes/api/cms/delete-book.ts": {
    id: "routes/api/cms/delete-book";
    page: "/api/cms/delete-book";
  };
  "routes/api/cms/edit-book.ts": {
    id: "routes/api/cms/edit-book";
    page: "/api/cms/edit-book";
  };
  "routes/api/cms/edit-book-genres.ts": {
    id: "routes/api/cms/edit-book-genres";
    page: "/api/cms/edit-book-genres";
  };
  "routes/api/cms/edit-book-authors.ts": {
    id: "routes/api/cms/edit-book-authors";
    page: "/api/cms/edit-book-authors";
  };
  "routes/api/set-book-status.ts": {
    id: "routes/api/set-book-status";
    page: "/api/set-book-status";
  };
  "routes/api/unset-book-status.ts": {
    id: "routes/api/unset-book-status";
    page: "/api/unset-book-status";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "common": typeof import("./app/routes/layout.tsx");
  "routes/home/home": typeof import("./app/routes/home/home.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/book/book": typeof import("./app/routes/book/book.tsx");
  "profile-layout": typeof import("./app/routes/profile/profile.tsx");
  "routes/profile/tracking/to-read": typeof import("./app/routes/profile/tracking/to-read.tsx");
  "routes/profile/tracking/completed": typeof import("./app/routes/profile/tracking/completed.tsx");
  "routes/profile/tracking/dropped": typeof import("./app/routes/profile/tracking/dropped.tsx");
  "routes/profile/tracking/on-hold": typeof import("./app/routes/profile/tracking/on-hold.tsx");
  "routes/profile/tracking/reading": typeof import("./app/routes/profile/tracking/reading.tsx");
  "routes/profile/cms/genres/genres": typeof import("./app/routes/profile/cms/genres/genres.tsx");
  "routes/profile/cms/authors/authors": typeof import("./app/routes/profile/cms/authors/authors.tsx");
  "routes/profile/cms/books/books": typeof import("./app/routes/profile/cms/books/books.tsx");
  "routes/api/sign-in": typeof import("./app/routes/api/sign-in.ts");
  "routes/api/sign-up": typeof import("./app/routes/api/sign-up.ts");
  "routes/api/logout": typeof import("./app/routes/api/logout.ts");
  "routes/api/send-feedback": typeof import("./app/routes/api/send-feedback.ts");
  "routes/api/cms/create-genre": typeof import("./app/routes/api/cms/create-genre.ts");
  "routes/api/cms/delete-genre": typeof import("./app/routes/api/cms/delete-genre.ts");
  "routes/api/cms/edit-genre": typeof import("./app/routes/api/cms/edit-genre.ts");
  "routes/api/cms/create-author": typeof import("./app/routes/api/cms/create-author.ts");
  "routes/api/cms/delete-author": typeof import("./app/routes/api/cms/delete-author.ts");
  "routes/api/cms/edit-author": typeof import("./app/routes/api/cms/edit-author.ts");
  "routes/api/cms/create-book": typeof import("./app/routes/api/cms/create-book.ts");
  "routes/api/cms/delete-book": typeof import("./app/routes/api/cms/delete-book.ts");
  "routes/api/cms/edit-book": typeof import("./app/routes/api/cms/edit-book.ts");
  "routes/api/cms/edit-book-genres": typeof import("./app/routes/api/cms/edit-book-genres.ts");
  "routes/api/cms/edit-book-authors": typeof import("./app/routes/api/cms/edit-book-authors.ts");
  "routes/api/set-book-status": typeof import("./app/routes/api/set-book-status.ts");
  "routes/api/unset-book-status": typeof import("./app/routes/api/unset-book-status.ts");
};